// This file is generated by drizzle-kit / used for expo-sqlite migrations
import journal from './meta/_journal.json';
import m0000 from './0000_init.sql';

export default {
  journal,
  migrations: {
    m0000,
  },
};
