export interface SeedWord {
  word: string;
  category: string;
  difficulty: string;
}

/**
 * Built-in word bank used when there is no API key or OpenRouter is unreachable.
 * Roughly 15 words per category and difficulty; duplicates within a category are removed.
 */
export const SEED_WORDS: SeedWord[] = [
  // Everyday English
  { word: 'calendar', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'umbrella', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'grocery', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'library', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'kitchen', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'bicycle', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'jacket', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'pillow', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'window', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'garden', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'breakfast', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'holiday', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'neighbour', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'sandwich', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'weather', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'schedule', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'receipt', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'restaurant', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'appointment', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'envelope', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'address', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'insurance', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'discount', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'reservation', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'subscription', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'exercise', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'vegetable', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'temperature', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'invitation', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'delivery', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'neighbourhood', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'convenient', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'recommendation', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'necessary', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'occasionally', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'miscellaneous', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'entrepreneur', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'restaurateur', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'acquaintance', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'embarrassment', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'guarantee', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'conscientious', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'rhythm', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'accommodate', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'committee', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'neighborhood', category: 'IELTS Listening', difficulty: 'Hard' },

  // IELTS Listening
  { word: 'brochure', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'survey', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'booking', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'fitness', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'lecture', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'tutor', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'museum', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'ticket', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'telephone', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'number', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'postcode', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'passport', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'tourist', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'feedback', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'project', category: 'IELTS Listening', difficulty: 'Easy' },
  { word: 'environment', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'government', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'laboratory', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'questionnaire', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'maintenance', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'registration', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'membership', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'deposit', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'accommodation', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'excursion', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'itinerary', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'facility', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'equipment', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'application', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'reference', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'temperature', category: 'IELTS Listening', difficulty: 'Medium' },
  { word: 'parliament', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'catalogue', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'programme', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'technique', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'architecture', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'psychology', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'hypothesis', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'bibliography', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'sustainable', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'vocabulary', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'anonymous', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'archaeology', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'committee', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'curriculum', category: 'IELTS Listening', difficulty: 'Hard' },
  { word: 'thoroughly', category: 'IELTS Listening', difficulty: 'Hard' },

  // Education
  { word: 'student', category: 'Education', difficulty: 'Easy' },
  { word: 'teacher', category: 'Education', difficulty: 'Easy' },
  { word: 'lesson', category: 'Education', difficulty: 'Easy' },
  { word: 'exam', category: 'Education', difficulty: 'Easy' },
  { word: 'campus', category: 'Education', difficulty: 'Easy' },
  { word: 'degree', category: 'Education', difficulty: 'Easy' },
  { word: 'course', category: 'Education', difficulty: 'Easy' },
  { word: 'library', category: 'Education', difficulty: 'Easy' },
  { word: 'subject', category: 'Education', difficulty: 'Easy' },
  { word: 'notes', category: 'Education', difficulty: 'Easy' },
  { word: 'school', category: 'Education', difficulty: 'Easy' },
  { word: 'college', category: 'Education', difficulty: 'Easy' },
  { word: 'grade', category: 'Education', difficulty: 'Easy' },
  { word: 'essay', category: 'Education', difficulty: 'Easy' },
  { word: 'module', category: 'Education', difficulty: 'Easy' },
  { word: 'semester', category: 'Education', difficulty: 'Easy' },
  { word: 'tutorial', category: 'Education', difficulty: 'Easy' },
  { word: 'assignment', category: 'Education', difficulty: 'Easy' },
  { word: 'professor', category: 'Education', difficulty: 'Easy' },
  { word: 'assessment', category: 'Education', difficulty: 'Medium' },
  { word: 'scholarship', category: 'Education', difficulty: 'Medium' },
  { word: 'seminar', category: 'Education', difficulty: 'Medium' },
  { word: 'lecturer', category: 'Education', difficulty: 'Medium' },
  { word: 'graduate', category: 'Education', difficulty: 'Medium' },
  { word: 'research', category: 'Education', difficulty: 'Medium' },
  { word: 'deadline', category: 'Education', difficulty: 'Medium' },
  { word: 'dissertation', category: 'Education', difficulty: 'Medium' },
  { word: 'attendance', category: 'Education', difficulty: 'Medium' },
  { word: 'faculty', category: 'Education', difficulty: 'Medium' },
  { word: 'timetable', category: 'Education', difficulty: 'Medium' },
  { word: 'bursary', category: 'Education', difficulty: 'Medium' },
  { word: 'curriculum', category: 'Education', difficulty: 'Hard' },
  { word: 'bibliography', category: 'Education', difficulty: 'Hard' },
  { word: 'plagiarism', category: 'Education', difficulty: 'Hard' },
  { word: 'undergraduate', category: 'Education', difficulty: 'Hard' },
  { word: 'postgraduate', category: 'Education', difficulty: 'Hard' },
  { word: 'vocational', category: 'Education', difficulty: 'Hard' },
  { word: 'extracurricular', category: 'Education', difficulty: 'Hard' },
  { word: 'pedagogy', category: 'Education', difficulty: 'Hard' },
  { word: 'prerequisite', category: 'Education', difficulty: 'Hard' },
  { word: 'laboratory', category: 'Education', difficulty: 'Hard' },
  { word: 'thesis', category: 'Education', difficulty: 'Hard' },
  { word: 'methodology', category: 'Education', difficulty: 'Hard' },
  { word: 'certificate', category: 'Education', difficulty: 'Hard' },
  { word: 'accreditation', category: 'Education', difficulty: 'Hard' },
  { word: 'dyslexia', category: 'Education', difficulty: 'Hard' },

  // Accommodation
  { word: 'apartment', category: 'Accommodation', difficulty: 'Easy' },
  { word: 'balcony', category: 'Accommodation', difficulty: 'Easy' },
  { word: 'bedroom', category: 'Accommodation', difficulty: 'Easy' },
  { word: 'kitchen', category: 'Accommodation', difficulty: 'Easy' },
  { word: 'garden', category: 'Accommodation', difficulty: 'Easy' },
  { word: 'garage', category: 'Accommodation', difficulty: 'Easy' },
  { word: 'bathroom', category: 'Accommodation', difficulty: 'Easy' },
  { word: 'landlord', category: 'Accommodation', difficulty: 'Easy' },
  { word: 'tenant', category: 'Accommodation', difficulty: 'Easy' },
  { word: 'rent', category: 'Accommodation', difficulty: 'Easy' },
  { word: 'lounge', category: 'Accommodation', difficulty: 'Easy' },
  { word: 'studio', category: 'Accommodation', difficulty: 'Easy' },
  { word: 'flat', category: 'Accommodation', difficulty: 'Easy' },
  { word: 'house', category: 'Accommodation', difficulty: 'Easy' },
  { word: 'room', category: 'Accommodation', difficulty: 'Easy' },
  { word: 'suburb', category: 'Accommodation', difficulty: 'Easy' },
  { word: 'dormitory', category: 'Accommodation', difficulty: 'Medium' },
  { word: 'residence', category: 'Accommodation', difficulty: 'Medium' },
  { word: 'furnished', category: 'Accommodation', difficulty: 'Medium' },
  { word: 'utilities', category: 'Accommodation', difficulty: 'Medium' },
  { word: 'deposit', category: 'Accommodation', difficulty: 'Medium' },
  { word: 'contract', category: 'Accommodation', difficulty: 'Medium' },
  { word: 'lease', category: 'Accommodation', difficulty: 'Medium' },
  { word: 'heating', category: 'Accommodation', difficulty: 'Medium' },
  { word: 'laundry', category: 'Accommodation', difficulty: 'Medium' },
  { word: 'security', category: 'Accommodation', difficulty: 'Medium' },
  { word: 'elevator', category: 'Accommodation', difficulty: 'Medium' },
  { word: 'neighbour', category: 'Accommodation', difficulty: 'Medium' },
  { word: 'vacancy', category: 'Accommodation', difficulty: 'Medium' },
  { word: 'shared', category: 'Accommodation', difficulty: 'Medium' },
  { word: 'basement', category: 'Accommodation', difficulty: 'Medium' },
  { word: 'accommodation', category: 'Accommodation', difficulty: 'Hard' },
  { word: 'maisonette', category: 'Accommodation', difficulty: 'Hard' },
  { word: 'refurbishment', category: 'Accommodation', difficulty: 'Hard' },
  { word: 'inventory', category: 'Accommodation', difficulty: 'Hard' },
  { word: 'tenancy', category: 'Accommodation', difficulty: 'Hard' },
  { word: 'conservatory', category: 'Accommodation', difficulty: 'Hard' },
  { word: 'bungalow', category: 'Accommodation', difficulty: 'Hard' },
  { word: 'ventilation', category: 'Accommodation', difficulty: 'Hard' },
  { word: 'insulation', category: 'Accommodation', difficulty: 'Hard' },
  { word: 'renovation', category: 'Accommodation', difficulty: 'Hard' },
  { word: 'landlady', category: 'Accommodation', difficulty: 'Hard' },
  { word: 'occupancy', category: 'Accommodation', difficulty: 'Hard' },
  { word: 'leasehold', category: 'Accommodation', difficulty: 'Hard' },
  { word: 'freehold', category: 'Accommodation', difficulty: 'Hard' },
  { word: 'plumbing', category: 'Accommodation', difficulty: 'Hard' },
  { word: 'residential', category: 'Accommodation', difficulty: 'Hard' },

  // Transport
  { word: 'train', category: 'Transport', difficulty: 'Easy' },
  { word: 'bus', category: 'Transport', difficulty: 'Easy' },
  { word: 'taxi', category: 'Transport', difficulty: 'Easy' },
  { word: 'ticket', category: 'Transport', difficulty: 'Easy' },
  { word: 'airport', category: 'Transport', difficulty: 'Easy' },
  { word: 'station', category: 'Transport', difficulty: 'Easy' },
  { word: 'platform', category: 'Transport', difficulty: 'Easy' },
  { word: 'bridge', category: 'Transport', difficulty: 'Easy' },
  { word: 'road', category: 'Transport', difficulty: 'Easy' },
  { word: 'driver', category: 'Transport', difficulty: 'Easy' },
  { word: 'tram', category: 'Transport', difficulty: 'Easy' },
  { word: 'ferry', category: 'Transport', difficulty: 'Easy' },
  { word: 'bicycle', category: 'Transport', difficulty: 'Easy' },
  { word: 'journey', category: 'Transport', difficulty: 'Easy' },
  { word: 'luggage', category: 'Transport', difficulty: 'Easy' },
  { word: 'timetable', category: 'Transport', difficulty: 'Easy' },
  { word: 'commute', category: 'Transport', difficulty: 'Easy' },
  { word: 'underground', category: 'Transport', difficulty: 'Easy' },
  { word: 'departure', category: 'Transport', difficulty: 'Easy' },
  { word: 'passenger', category: 'Transport', difficulty: 'Medium' },
  { word: 'pedestrian', category: 'Transport', difficulty: 'Medium' },
  { word: 'terminal', category: 'Transport', difficulty: 'Medium' },
  { word: 'arrival', category: 'Transport', difficulty: 'Medium' },
  { word: 'motorway', category: 'Transport', difficulty: 'Medium' },
  { word: 'roundabout', category: 'Transport', difficulty: 'Medium' },
  { word: 'pavement', category: 'Transport', difficulty: 'Medium' },
  { word: 'junction', category: 'Transport', difficulty: 'Medium' },
  { word: 'carriage', category: 'Transport', difficulty: 'Medium' },
  { word: 'boarding', category: 'Transport', difficulty: 'Medium' },
  { word: 'subway', category: 'Transport', difficulty: 'Medium' },
  { word: 'pedestrianised', category: 'Transport', difficulty: 'Hard' },
  { word: 'congestion', category: 'Transport', difficulty: 'Hard' },
  { word: 'itinerary', category: 'Transport', difficulty: 'Hard' },
  { word: 'connection', category: 'Transport', difficulty: 'Hard' },
  { word: 'jaywalking', category: 'Transport', difficulty: 'Hard' },
  { word: 'commuter', category: 'Transport', difficulty: 'Hard' },
  { word: 'turbulence', category: 'Transport', difficulty: 'Hard' },
  { word: 'embarkation', category: 'Transport', difficulty: 'Hard' },
  { word: 'stopover', category: 'Transport', difficulty: 'Hard' },
  { word: 'intersection', category: 'Transport', difficulty: 'Hard' },
  { word: 'transportation', category: 'Transport', difficulty: 'Hard' },
  { word: 'disembark', category: 'Transport', difficulty: 'Hard' },
  { word: 'reservation', category: 'Transport', difficulty: 'Hard' },
  { word: 'punctuality', category: 'Transport', difficulty: 'Hard' },
  { word: 'quarantine', category: 'Transport', difficulty: 'Hard' },
  { word: 'locomotive', category: 'Transport', difficulty: 'Hard' },

  // Work
  { word: 'office', category: 'Work', difficulty: 'Easy' },
  { word: 'manager', category: 'Work', difficulty: 'Easy' },
  { word: 'salary', category: 'Work', difficulty: 'Easy' },
  { word: 'staff', category: 'Work', difficulty: 'Easy' },
  { word: 'shift', category: 'Work', difficulty: 'Easy' },
  { word: 'boss', category: 'Work', difficulty: 'Easy' },
  { word: 'team', category: 'Work', difficulty: 'Easy' },
  { word: 'career', category: 'Work', difficulty: 'Easy' },
  { word: 'job', category: 'Work', difficulty: 'Easy' },
  { word: 'meeting', category: 'Work', difficulty: 'Easy' },
  { word: 'client', category: 'Work', difficulty: 'Easy' },
  { word: 'report', category: 'Work', difficulty: 'Easy' },
  { word: 'email', category: 'Work', difficulty: 'Easy' },
  { word: 'desk', category: 'Work', difficulty: 'Easy' },
  { word: 'lunch', category: 'Work', difficulty: 'Easy' },
  { word: 'management', category: 'Work', difficulty: 'Easy' },
  { word: 'employment', category: 'Work', difficulty: 'Easy' },
  { word: 'colleague', category: 'Work', difficulty: 'Medium' },
  { word: 'supervisor', category: 'Work', difficulty: 'Medium' },
  { word: 'conference', category: 'Work', difficulty: 'Medium' },
  { word: 'presentation', category: 'Work', difficulty: 'Medium' },
  { word: 'interview', category: 'Work', difficulty: 'Medium' },
  { word: 'promotion', category: 'Work', difficulty: 'Medium' },
  { word: 'contract', category: 'Work', difficulty: 'Medium' },
  { word: 'resignation', category: 'Work', difficulty: 'Medium' },
  { word: 'overtime', category: 'Work', difficulty: 'Medium' },
  { word: 'training', category: 'Work', difficulty: 'Medium' },
  { word: 'vacancy', category: 'Work', difficulty: 'Medium' },
  { word: 'employee', category: 'Work', difficulty: 'Medium' },
  { word: 'deadline', category: 'Work', difficulty: 'Medium' },
  { word: 'negotiation', category: 'Work', difficulty: 'Hard' },
  { word: 'redundancy', category: 'Work', difficulty: 'Hard' },
  { word: 'entrepreneur', category: 'Work', difficulty: 'Hard' },
  { word: 'accountant', category: 'Work', difficulty: 'Hard' },
  { word: 'recruitment', category: 'Work', difficulty: 'Hard' },
  { word: 'pension', category: 'Work', difficulty: 'Hard' },
  { word: 'appraisal', category: 'Work', difficulty: 'Hard' },
  { word: 'apprenticeship', category: 'Work', difficulty: 'Hard' },
  { word: 'qualification', category: 'Work', difficulty: 'Hard' },
  { word: 'unemployment', category: 'Work', difficulty: 'Hard' },
  { word: 'procurement', category: 'Work', difficulty: 'Hard' },
  { word: 'bureaucracy', category: 'Work', difficulty: 'Hard' },
  { word: 'consultant', category: 'Work', difficulty: 'Hard' },
  { word: 'profitability', category: 'Work', difficulty: 'Hard' },
  { word: 'entitlement', category: 'Work', difficulty: 'Hard' },
  { word: 'remuneration', category: 'Work', difficulty: 'Hard' },

  // Places
  { word: 'park', category: 'Places', difficulty: 'Easy' },
  { word: 'beach', category: 'Places', difficulty: 'Easy' },
  { word: 'market', category: 'Places', difficulty: 'Easy' },
  { word: 'museum', category: 'Places', difficulty: 'Easy' },
  { word: 'bridge', category: 'Places', difficulty: 'Easy' },
  { word: 'castle', category: 'Places', difficulty: 'Easy' },
  { word: 'river', category: 'Places', difficulty: 'Easy' },
  { word: 'street', category: 'Places', difficulty: 'Easy' },
  { word: 'garden', category: 'Places', difficulty: 'Easy' },
  { word: 'airport', category: 'Places', difficulty: 'Easy' },
  { word: 'harbour', category: 'Places', difficulty: 'Easy' },
  { word: 'theatre', category: 'Places', difficulty: 'Easy' },
  { word: 'cinema', category: 'Places', difficulty: 'Easy' },
  { word: 'stadium', category: 'Places', difficulty: 'Easy' },
  { word: 'hotel', category: 'Places', difficulty: 'Easy' },
  { word: 'monument', category: 'Places', difficulty: 'Easy' },
  { word: 'suburb', category: 'Places', difficulty: 'Easy' },
  { word: 'cathedral', category: 'Places', difficulty: 'Medium' },
  { word: 'exhibition', category: 'Places', difficulty: 'Medium' },
  { word: 'gymnasium', category: 'Places', difficulty: 'Medium' },
  { word: 'boulevard', category: 'Places', difficulty: 'Medium' },
  { word: 'gallery', category: 'Places', difficulty: 'Medium' },
  { word: 'aquarium', category: 'Places', difficulty: 'Medium' },
  { word: 'peninsula', category: 'Places', difficulty: 'Medium' },
  { word: 'waterfall', category: 'Places', difficulty: 'Medium' },
  { word: 'fountain', category: 'Places', difficulty: 'Medium' },
  { word: 'playground', category: 'Places', difficulty: 'Medium' },
  { word: 'reservoir', category: 'Places', difficulty: 'Medium' },
  { word: 'district', category: 'Places', difficulty: 'Medium' },
  { word: 'promenade', category: 'Places', difficulty: 'Medium' },
  { word: 'amphitheatre', category: 'Places', difficulty: 'Hard' },
  { word: 'mausoleum', category: 'Places', difficulty: 'Hard' },
  { word: 'archipelago', category: 'Places', difficulty: 'Hard' },
  { word: 'observatory', category: 'Places', difficulty: 'Hard' },
  { word: 'conservatory', category: 'Places', difficulty: 'Hard' },
  { word: 'metropolitan', category: 'Places', difficulty: 'Hard' },
  { word: 'pedestrian', category: 'Places', difficulty: 'Hard' },
  { word: 'embassy', category: 'Places', difficulty: 'Hard' },
  { word: 'cemetery', category: 'Places', difficulty: 'Hard' },
  { word: 'lighthouse', category: 'Places', difficulty: 'Hard' },
  { word: 'monastery', category: 'Places', difficulty: 'Hard' },
  { word: 'renaissance', category: 'Places', difficulty: 'Hard' },
  { word: 'thoroughfare', category: 'Places', difficulty: 'Hard' },
  { word: 'skyscraper', category: 'Places', difficulty: 'Hard' },

  // Names
  { word: 'James', category: 'Names', difficulty: 'Easy' },
  { word: 'Emma', category: 'Names', difficulty: 'Easy' },
  { word: 'Oliver', category: 'Names', difficulty: 'Easy' },
  { word: 'Sophie', category: 'Names', difficulty: 'Easy' },
  { word: 'Henry', category: 'Names', difficulty: 'Easy' },
  { word: 'Grace', category: 'Names', difficulty: 'Easy' },
  { word: 'Thomas', category: 'Names', difficulty: 'Easy' },
  { word: 'Alice', category: 'Names', difficulty: 'Easy' },
  { word: 'Daniel', category: 'Names', difficulty: 'Easy' },
  { word: 'Laura', category: 'Names', difficulty: 'Easy' },
  { word: 'Peter', category: 'Names', difficulty: 'Easy' },
  { word: 'Helen', category: 'Names', difficulty: 'Easy' },
  { word: 'David', category: 'Names', difficulty: 'Easy' },
  { word: 'Sarah', category: 'Names', difficulty: 'Easy' },
  { word: 'Simon', category: 'Names', difficulty: 'Easy' },
  { word: 'Jonathan', category: 'Names', difficulty: 'Easy' },
  { word: 'Christopher', category: 'Names', difficulty: 'Medium' },
  { word: 'Elizabeth', category: 'Names', difficulty: 'Medium' },
  { word: 'Alexander', category: 'Names', difficulty: 'Medium' },
  { word: 'Katherine', category: 'Names', difficulty: 'Medium' },
  { word: 'Margaret', category: 'Names', difficulty: 'Medium' },
  { word: 'Gabrielle', category: 'Names', difficulty: 'Medium' },
  { word: 'Nicholas', category: 'Names', difficulty: 'Medium' },
  { word: 'Rebecca', category: 'Names', difficulty: 'Medium' },
  { word: 'Theodore', category: 'Names', difficulty: 'Medium' },
  { word: 'Isabelle', category: 'Names', difficulty: 'Medium' },
  { word: 'Benjamin', category: 'Names', difficulty: 'Medium' },
  { word: 'Victoria', category: 'Names', difficulty: 'Medium' },
  { word: 'Matthew', category: 'Names', difficulty: 'Medium' },
  { word: 'Josephine', category: 'Names', difficulty: 'Medium' },
  { word: 'Montgomery', category: 'Names', difficulty: 'Hard' },
  { word: 'Archibald', category: 'Names', difficulty: 'Hard' },
  { word: 'Wojciech', category: 'Names', difficulty: 'Hard' },
  { word: 'Siobhan', category: 'Names', difficulty: 'Hard' },
  { word: 'Anastasia', category: 'Names', difficulty: 'Hard' },
  { word: 'Bartholomew', category: 'Names', difficulty: 'Hard' },
  { word: 'Fitzgerald', category: 'Names', difficulty: 'Hard' },
  { word: 'Guillermo', category: 'Names', difficulty: 'Hard' },
  { word: 'Ravensworth', category: 'Names', difficulty: 'Hard' },
  { word: 'Mackenzie', category: 'Names', difficulty: 'Hard' },
  { word: 'Cholmondeley', category: 'Names', difficulty: 'Hard' },
  { word: 'Saoirse', category: 'Names', difficulty: 'Hard' },
  { word: 'Ptolemy', category: 'Names', difficulty: 'Hard' },
  { word: 'Worcester', category: 'Names', difficulty: 'Hard' },
  { word: 'Beauchamp', category: 'Names', difficulty: 'Hard' },

];

